services:
  stellar-local:
    image: stellar/quickstart:testing
    container_name: stellar-local
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    environment:
      - NETWORK=local
    volumes:
      - stellar-local-data:/var/lib/stellar
    restart: "no"
    command: --standalone --enable-soroban-rpc

volumes:
  stellar-local-data:
